framework:
    html_sanitizer:
        sanitizers:
            app.content_sanitizer:
                allow_safe_elements: true
                allow_elements:
                    a: ['href', 'title', 'target', 'rel']
                    img: ['src', 'alt', 'title', 'width', 'height', 'class', 'style']
                    figure: ['class', 'style']
                    iframe: ['src', 'width', 'height', 'frameborder', 'allow', 'allowfullscreen', 'title']
                allowed_media_schemes: ['https']
                # Images: all HTTPS domains allowed
                # Iframes: restricted by IframeSrcSanitizer to video platforms only
                allow_relative_medias: true
                force_https_urls: true
                with_attribute_sanitizers:
                    - App\HtmlSanitizer\IframeSrcSanitizer
